### PR TITLE
Design system

### PR DESCRIPTION
**Pull request by VirginiaDooley**
Status: https://stage.democracyclub.org.uk/
- [x] Install the design system
Convert
- [x] Home Page
- [x] Header 
- [x] Footer
- [x] Funding
- [x] About
- [x] Projects
- [x] Reports List
- [x] [2021 Report app ](https://stage.democracyclub.org.uk/report_2021/)
- [x] Old Reports
- [x] Report Detail (Template with includes for graphs, tables, contents, text)
- [x] Past Projects
- [x] Quests nav links (more removal work in https://github.com/DemocracyClub/Website/issues/371)
- [x] Blog
- [x] Forms

Not in this PR 
- Related, all navigation links are exceptionally small on mobile
- Pagination for blogs

### CODE REVIEW

**Comment by VirginiaDooley** [comment]
@symroe Currently, the site has a narrow main body for the pages connected to the main nav - although the home page is fuller width. If we change this to use full width to match the home page, we can make use of grids for things like projects and reports. What do you think?

**Comment by symroe** [comment]
> @symroe Currently, the site has a narrow main body for the pages connected to the main nav - although the home page is fuller width. If we change this to use full width to match the home page, we can make use of grids for things like projects and reports. What do you think?

I'm happy to just conform to whatever the design system gives us - I don't think we should special case this site if we can help it!

**Comment by chris48s** [comment]
> Forms (Mailing List) have been excluded from this work until `dc_signup_form` is upgraded with `dc_design_system`.

FWIW there are two ways in which dc_signup_form "requires" dc_base_theme.

* One is that the templates use the `| dc_form` custom template filter for rendering forms - this is a hard requirement.
* The other is a soft dependency: dc_signup_form renders some HTML with classes/ids e.g: `<div class="card">` etc and it assumes you are going to provide your own styling for them. dc_signup_form does not provide you with any styling for the HTML it renders. dc_base_theme knows how to style these elements, but you could provide your own styling instead.

So all it really cares about is that there is a `| dc_form` filter that exists and can render a django form object (not where it came from, as sucj). If you can provide (or shim) a `| dc_form` filter or include one in the design_system lib, you should be able to use the lib as it stands with a different theme (untested).

**Comment by VirginiaDooley** [comment]
The failed build errors are breaking changes for local env server so I've left them in for now until we configure settings for local vs staging.

**Comment by VirginiaDooley** [comment]
Requires follow up:[ This commit](https://github.com/DemocracyClub/Website/pull/370/commits/21d6eb740660bc6b20d4871c05ceed966dd9b6cd) introduces a breaking change for the mailing list form, which is needed for the report stick nav to work.

**Comment by VirginiaDooley** [comment]
> Requires follow up:[ This commit](https://github.com/DemocracyClub/Website/pull/370/commits/21d6eb740660bc6b20d4871c05ceed966dd9b6cd) introduces a breaking change for the mailing list form, which is needed for the report stick nav to work.

This issue was eliminated when Foundation was removed with [report system refactor](https://github.com/DemocracyClub/Website/pull/370/commits/c3012b820da8d6f73851880df73a32bde98299d9).

**Comment by VirginiaDooley** [comment]
I've turned `djhtml` off for the report files that contain markdown in [d332391](https://github.com/DemocracyClub/Website/pull/370/commits/d3323917ccd172e26e3b114543879731532fa3ff).

**Pull request merged**
