### PR TITLE
Problem statement on home page

### PR DESCRIPTION
**Pull request by VirginiaDooley**
To test: Ask yourself, 1) does this change answer the question of "What if DC didn't exist?"; 2) is this easy to present as an elevator pitch?; 3) does this accurately capture what DC does today? 

`/`
Screenshot 2023-10-17 at 12 40 40 PM

`/about`
Screenshot 2023-10-17 at 12 44 37 PM

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205677936610790

### CODE REVIEW

**Comment by pmk01** [comment]
This is great! A suggested edit to final sentence:

Democracy Club makes voter information more accessible, user-friendly, and readily available online, enhancing the democratic process and boosting voter engagement.

**Comment by pmk01** [comment]
Reading it back, it maybe change the third 'voter' ('voter information more accessible') to 'election', to minimise repetition. Maybe the third 'Democracy Club' could be changed to 'we', but perhaps am overthinking it.

**Comment by pmk01** [comment]
(sorry, text editing via github comments is always painful 😅 )

**Comment by VirginiaDooley** [comment]
Nope, good edits.

*Virginia Dooley*

Developer


Democracy Club | democracyclub.org.uk

Twitter | @democlub <https://twitter.com/democlub>

Mastodon | @DemocracyClub ***@***.***>

**Comment by VirginiaDooley** [comment]
> Reading it back, it maybe change the third 'voter' ('voter information more accessible') to 'election', to minimise repetition. Maybe the third 'Democracy Club' could be changed to 'we', but perhaps am overthinking it.

"Our digital tools make information more accessible..."?

**Comment by pmk01** [comment]
Yes, much better, let's go with that.

**Comment by symroe** [comment]
(Not sure this is the best way to revise this, maybe a call and a Google doc? however...)

I think the above is a huge improvement on what we currently have, but I wanted to have a play around to see if I could make it shorter. 

First, a tiny point, but "election data" might get confused with polling and other forms of psephology. I think "voting information data" is clearer. I also try to avoid "voter information" in case we're confused with Cambridge Analytica etc. 

I also think we can take our name out of the heading? 

This is what I came up with:

image

**Comment by symroe** [comment]
This still isn't really problem statement, but it's a good description of what we do at least!

**Comment by VirginiaDooley** [comment]
> This still isn't really problem statement, but it's a good description of what we do at least!

I like all these changes, but I think we need the problem statement. 

Screenshot 2023-10-17 at 12 40 40 PM

**Pull request merged**
