### PR TITLE
Merge widgets into one section

### PR DESCRIPTION
**Pull request by VirginiaDooley**
- Create new urls for shared widget template
- Reinstate 'our work' in the header nav
- Reroute councils to the shared widget page
- Add with or without candidates options to the widget generator

To test, visit https://stage.democracyclub.org.uk/
Screenshot 2023-10-16 at 2 54 24 PM

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205601956377787

### CODE REVIEW

**Comment by symroe** [comment]
The "for councils" section still has the widget sub-navigation, with no way to get back to the EMS upload page once you click on one of the sub-navs.

I think the general rule should be that the left-most sub-nav should be the "root" page of the section, so either:

1. Remove the sub-nav (this is only about uploading data) or
2. Add another tab to the sub-nav to allow people to get back to the landing page (upload your data?)

@pmk01 how useful is that page nowadays, especially as we have https://wheredoivote.co.uk/uploads/about/?

**Comment by symroe** [comment]
Widget page is :+1: though! Do we need to call them "widgets"? Is that talking about the different options, or the ability to make a custom one?

**Comment by pmk01** [comment]
Ah, good catch Sym. We should call them something else on both the 'our work' page, and the lookup.

Maybe "Free election lookup for your website", or "Free interactive polling station finder" or some combination of those things. We should use the word 'widget' _somewhere_, but not too prominently.

**Comment by pmk01** [comment]
> > Free election lookup for your website
> 
> We can make this change, but then we should probably make it in every report or any reference anywhere, otherwise historical info referring to 'widget' will be very confusing.

That's why I suggested keeping the word 'widget' on the page, eg. at https://stage.democracyclub.org.uk/projects/:

[Free election lookup for your website](https://stage.democracyclub.org.uk/projects/election-widget/)
We offer a free election 'widget' for use on your website.

**Comment by VirginiaDooley** [comment]
> a5c8b8f

Fixed with https://github.com/DemocracyClub/Website/pull/747/commits/a5c8b8f8ca5c74c906a853896f9128e43ecd470e

**Comment by VirginiaDooley** [comment]
> Widget page is 👍 though! Do we need to call them "widgets"? Is that talking about the different options, or the ability to make a custom one?

Fixed with https://github.com/DemocracyClub/Website/pull/747/commits/a5c8b8f8ca5c74c906a853896f9128e43ecd470e

**Pull request merged**
