### PR TITLE
New design

### PR DESCRIPTION
**Pull request by tfgg**
Fairly mangled. Everything needs refactoring in sass. Mailing list appears to be working. Pages needed for post-join (to give actions) and an explainer for Data for Democracy.

image

### CODE REVIEW

**Comment by JoeMitchell** [comment]
YES TIM!!!

**Comment by andylolz** [comment]
The homepage looks lovely now :)

The [projects page](https://democracyclub.org.uk/projects/) really needs a revamp. Particularly given it is more prominent now, since “Data for Democracy” links through to it.

**Comment by andylolz** [comment]
The signup form in the footer has “name” and “email” fields, whereas the “Join our club” one just has “email”. It also looks like it’s something different to the mailing list (I had to inspect elements to figure out it wasn’t.)

**Comment by tfgg** [comment]
Yup, that's up next, probably at /data/. Also the page you land on after signing up for the mailing list, to redirect people to tasks to do next.

**Comment by andylolz** [comment]
The signup form in the footer has “name” and “email” fields, whereas the “Join our club” one just has “email”. It also looks like it’s something different to the mailing list (I had to inspect elements to figure out it wasn’t.)

**Pull request merged**
